# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.24},
    {id: 1, size: 0.24},
    {id: 2, size: 0.24},
    {id: 3, size: 0.24}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
#    {
#      name: 'tag0123',
#      layout:
#        [
#{id: 0, size: 0.24, x: 0.000000, y: 0.000000, z: -0.000000, qw: 1.000000, qx: 0.000000, qy: 0.000000, qz: 0.000000},
#{id: 1, size: 0.24, x: -0.001816, y: 1.531080, z: -0.011542, qw: 0.999857, qx: -0.016509, qy: 0.003586, qz: -0.001150},
#{id: 2, size: 0.24, x: 2.610868, y: -0.000759, z: 0.000000, qw: 0.999946, qx: 0.001334, qy: -0.010243, qz: -0.001260},
#{id: 3, size: 0.24, x: 2.609633, y: 1.475618, z: 0.074151, qw: 0.999307, qx: -0.008378, qy: -0.033844, qz: 0.013010}
#        ]
#    }
  ]
